/* ==========================================================
   BANCO DE PALABRAS — MODO TILDES (Estudio y Reto)
   Generado a partir del banco revisado de Mi Acordeón.
   p = forma que se muestra · ok = respuesta correcta
   d = distractores · cat = categoría · syl = sílabas
   nota = aclaración que aparece después de responder
   Las diacríticas van dentro de una frase (…) para que
   haya contexto y solo una respuesta sea correcta.
=========================================================== */
const DB_TILDES=[
  {p:"camion",ok:"camión",d:["camion","cámion"],cat:"AGUDA",syl:"ca-mión"},
  {p:"cancion",ok:"canción",d:["cancion","cáncion"],cat:"AGUDA",syl:"can-ción"},
  {p:"cafe",ok:"café",d:["cafe","cáfe"],cat:"AGUDA",syl:"ca-fé"},
  {p:"sofa",ok:"sofá",d:["sofa","sófa"],cat:"AGUDA",syl:"so-fá"},
  {p:"boton",ok:"botón",d:["boton","bóton"],cat:"AGUDA",syl:"bo-tón"},
  {p:"jardin",ok:"jardín",d:["jardin","járdin"],cat:"AGUDA",syl:"jar-dín"},
  {p:"avion",ok:"avión",d:["avion","ávion"],cat:"AGUDA",syl:"a-vión"},
  {p:"raton",ok:"ratón",d:["raton","ráton"],cat:"AGUDA",syl:"ra-tón"},
  {p:"corazon",ok:"corazón",d:["corazon","corázon"],cat:"AGUDA",syl:"co-ra-zón"},
  {p:"jamas",ok:"jamás",d:["jamas","jámas"],cat:"AGUDA",syl:"ja-más"},
  {p:"ademas",ok:"además",d:["ademas","adémas"],cat:"AGUDA",syl:"a-de-más"},
  {p:"balcon",ok:"balcón",d:["balcon","bálcon"],cat:"AGUDA",syl:"bal-cón"},
  {p:"sarten",ok:"sartén",d:["sarten","sárten"],cat:"AGUDA",syl:"sar-tén"},
  {p:"colibri",ok:"colibrí",d:["colibri","colíbri"],cat:"AGUDA",syl:"co-li-brí"},
  {p:"telon",ok:"telón",d:["telon","télon"],cat:"AGUDA",syl:"te-lón"},
  {p:"tabu",ok:"tabú",d:["tabu","tábu"],cat:"AGUDA",syl:"ta-bú"},
  {p:"despues",ok:"después",d:["despues","déspues"],cat:"AGUDA",syl:"des-pués"},
  {p:"leccion",ok:"lección",d:["leccion","léccion"],cat:"AGUDA",syl:"lec-ción"},
  {p:"aqui",ok:"aquí",d:["aqui","áqui"],cat:"AGUDA",syl:"a-quí"},
  {p:"salio",ok:"salió",d:["salio","sálio"],cat:"AGUDA",syl:"sa-lió"},
  {p:"comio",ok:"comió",d:["comio","cómio"],cat:"AGUDA",syl:"co-mió"},
  {p:"reloj",ok:"reloj",d:["relój","réloj"],cat:"AGUDA",syl:"re-loj",nota:"(Es aguda y termina en «j», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"papel",ok:"papel",d:["papél","pápel"],cat:"AGUDA",syl:"pa-pel",nota:"(Es aguda y termina en «l», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"azul",ok:"azul",d:["azúl","ázul"],cat:"AGUDA",syl:"a-zul",nota:"(Es aguda y termina en «l», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"ciudad",ok:"ciudad",d:["ciudád","ciúdad"],cat:"AGUDA",syl:"ciu-dad",nota:"(Es aguda y termina en «d», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"feliz",ok:"feliz",d:["felíz","féliz"],cat:"AGUDA",syl:"fe-liz",nota:"(Es aguda y termina en «z», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"verdad",ok:"verdad",d:["verdád","vérdad"],cat:"AGUDA",syl:"ver-dad",nota:"(Es aguda y termina en «d», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"comer",ok:"comer",d:["comér","cómer"],cat:"AGUDA",syl:"co-mer",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"cantar",ok:"cantar",d:["cantár","cántar"],cat:"AGUDA",syl:"can-tar",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"amor",ok:"amor",d:["amór","ámor"],cat:"AGUDA",syl:"a-mor",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"caracol",ok:"caracol",d:["caracól","carácol"],cat:"AGUDA",syl:"ca-ra-col",nota:"(Es aguda y termina en «l», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"nariz",ok:"nariz",d:["naríz","náriz"],cat:"AGUDA",syl:"na-riz",nota:"(Es aguda y termina en «z», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"animal",ok:"animal",d:["animál","anímal"],cat:"AGUDA",syl:"a-ni-mal",nota:"(Es aguda y termina en «l», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"señor",ok:"señor",d:["señór","séñor"],cat:"AGUDA",syl:"se-ñor",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"español",ok:"español",d:["españól","espáñol"],cat:"AGUDA",syl:"es-pa-ñol",nota:"(Es aguda y termina en «l», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"calor",ok:"calor",d:["calór","cálor"],cat:"AGUDA",syl:"ca-lor",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"pared",ok:"pared",d:["paréd","páred"],cat:"AGUDA",syl:"pa-red",nota:"(Es aguda y termina en «d», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"tambor",ok:"tambor",d:["tambór","támbor"],cat:"AGUDA",syl:"tam-bor",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"motor",ok:"motor",d:["motór","mótor"],cat:"AGUDA",syl:"mo-tor",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"acordeon",ok:"acordeón",d:["acordeon","acordéon"],cat:"AGUDA",syl:"a-cor-de-ón"},
  {p:"atencion",ok:"atención",d:["atencion","aténcion"],cat:"AGUDA",syl:"a-ten-ción"},
  {p:"emocion",ok:"emoción",d:["emocion","emócion"],cat:"AGUDA",syl:"e-mo-ción"},
  {p:"nacion",ok:"nación",d:["nacion","nácion"],cat:"AGUDA",syl:"na-ción"},
  {p:"pantalon",ok:"pantalón",d:["pantalon","pantálon"],cat:"AGUDA",syl:"pan-ta-lón"},
  {p:"cajon",ok:"cajón",d:["cajon","cájon"],cat:"AGUDA",syl:"ca-jón"},
  {p:"jabon",ok:"jabón",d:["jabon","jábon"],cat:"AGUDA",syl:"ja-bón"},
  {p:"algodon",ok:"algodón",d:["algodon","algódon"],cat:"AGUDA",syl:"al-go-dón"},
  {p:"maraton",ok:"maratón",d:["maraton","maráton"],cat:"AGUDA",syl:"ma-ra-tón"},
  {p:"balon",ok:"balón",d:["balon","bálon"],cat:"AGUDA",syl:"ba-lón"},
  {p:"tiburon",ok:"tiburón",d:["tiburon","tibúron"],cat:"AGUDA",syl:"ti-bu-rón"},
  {p:"escalon",ok:"escalón",d:["escalon","escálon"],cat:"AGUDA",syl:"es-ca-lón"},
  {p:"melon",ok:"melón",d:["melon","mélon"],cat:"AGUDA",syl:"me-lón"},
  {p:"cañon",ok:"cañón",d:["cañon","cáñon"],cat:"AGUDA",syl:"ca-ñón"},
  {p:"delfin",ok:"delfín",d:["delfin","délfin"],cat:"AGUDA",syl:"del-fín"},
  {p:"maletin",ok:"maletín",d:["maletin","malétin"],cat:"AGUDA",syl:"ma-le-tín"},
  {p:"calcetin",ok:"calcetín",d:["calcetin","calcétin"],cat:"AGUDA",syl:"cal-ce-tín"},
  {p:"jazmin",ok:"jazmín",d:["jazmin","jázmin"],cat:"AGUDA",syl:"jaz-mín"},
  {p:"boletin",ok:"boletín",d:["boletin","bolétin"],cat:"AGUDA",syl:"bo-le-tín"},
  {p:"pingüin",ok:"pingüín",d:["pingüin","píngüin"],cat:"AGUDA",syl:"pin-güín"},
  {p:"japones",ok:"japonés",d:["japones","japónes"],cat:"AGUDA",syl:"ja-po-nés"},
  {p:"frances",ok:"francés",d:["frances","fránces"],cat:"AGUDA",syl:"fran-cés"},
  {p:"interes",ok:"interés",d:["interes","intéres"],cat:"AGUDA",syl:"in-te-rés"},
  {p:"portugues",ok:"portugués",d:["portugues","portúgues"],cat:"AGUDA",syl:"por-tu-gués"},
  {p:"detras",ok:"detrás",d:["detras","détras"],cat:"AGUDA",syl:"de-trás"},
  {p:"atras",ok:"atrás",d:["atras","átras"],cat:"AGUDA",syl:"a-trás"},
  {p:"bambu",ok:"bambú",d:["bambu","bámbu"],cat:"AGUDA",syl:"bam-bú"},
  {p:"mani",ok:"maní",d:["mani","máni"],cat:"AGUDA",syl:"ma-ní"},
  {p:"menu",ok:"menú",d:["menu","ménu"],cat:"AGUDA",syl:"me-nú"},
  {p:"pure",ok:"puré",d:["pure","púre"],cat:"AGUDA",syl:"pu-ré"},
  {p:"corrio",ok:"corrió",d:["corrio","córrio"],cat:"AGUDA",syl:"co-rrió"},
  {p:"vivio",ok:"vivió",d:["vivio","vívio"],cat:"AGUDA",syl:"vi-vió"},
  {p:"bebio",ok:"bebió",d:["bebio","bébio"],cat:"AGUDA",syl:"be-bió"},
  {p:"aprendio",ok:"aprendió",d:["aprendio","apréndio"],cat:"AGUDA",syl:"a-pren-dió"},
  {p:"durmio",ok:"durmió",d:["durmio","dúrmio"],cat:"AGUDA",syl:"dur-mió"},
  {p:"subio",ok:"subió",d:["subio","súbio"],cat:"AGUDA",syl:"su-bió"},
  {p:"perdio",ok:"perdió",d:["perdio","pérdio"],cat:"AGUDA",syl:"per-dió"},
  {p:"crecio",ok:"creció",d:["crecio","crécio"],cat:"AGUDA",syl:"cre-ció"},
  {p:"recibio",ok:"recibió",d:["recibio","recíbio"],cat:"AGUDA",syl:"re-ci-bió"},
  {p:"decidio",ok:"decidió",d:["decidio","decídio"],cat:"AGUDA",syl:"de-ci-dió"},
  {p:"alli",ok:"allí",d:["alli","álli"],cat:"AGUDA",syl:"a-llí"},
  {p:"aca",ok:"acá",d:["aca","áca"],cat:"AGUDA",syl:"a-cá"},
  {p:"cinturon",ok:"cinturón",d:["cinturon","cintúron"],cat:"AGUDA",syl:"cin-tu-rón"},
  {p:"hospital",ok:"hospital",d:["hospitál","hospítal"],cat:"AGUDA",syl:"hos-pi-tal",nota:"(Es aguda y termina en «l», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"capital",ok:"capital",d:["capitál","capítal"],cat:"AGUDA",syl:"ca-pi-tal",nota:"(Es aguda y termina en «l», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"cristal",ok:"cristal",d:["cristál","crístal"],cat:"AGUDA",syl:"cris-tal",nota:"(Es aguda y termina en «l», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"pastel",ok:"pastel",d:["pastél","pástel"],cat:"AGUDA",syl:"pas-tel",nota:"(Es aguda y termina en «l», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"hotel",ok:"hotel",d:["hotél","hótel"],cat:"AGUDA",syl:"ho-tel",nota:"(Es aguda y termina en «l», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"abril",ok:"abril",d:["abríl","ábril"],cat:"AGUDA",syl:"a-bril",nota:"(Es aguda y termina en «l», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"barril",ok:"barril",d:["barríl","bárril"],cat:"AGUDA",syl:"ba-rril",nota:"(Es aguda y termina en «l», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"perejil",ok:"perejil",d:["perejíl","peréjil"],cat:"AGUDA",syl:"pe-re-jil",nota:"(Es aguda y termina en «l», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"lugar",ok:"lugar",d:["lugár","lúgar"],cat:"AGUDA",syl:"lu-gar",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"saltar",ok:"saltar",d:["saltár","sáltar"],cat:"AGUDA",syl:"sal-tar",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"correr",ok:"correr",d:["corrér","córrer"],cat:"AGUDA",syl:"co-rrer",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"dormir",ok:"dormir",d:["dormír","dórmir"],cat:"AGUDA",syl:"dor-mir",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"escribir",ok:"escribir",d:["escribír","escríbir"],cat:"AGUDA",syl:"es-cri-bir",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"aprender",ok:"aprender",d:["aprendér","aprénder"],cat:"AGUDA",syl:"a-pren-der",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"mujer",ok:"mujer",d:["mujér","mújer"],cat:"AGUDA",syl:"mu-jer",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"color",ok:"color",d:["colór","cólor"],cat:"AGUDA",syl:"co-lor",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"dolor",ok:"dolor",d:["dolór","dólor"],cat:"AGUDA",syl:"do-lor",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"sabor",ok:"sabor",d:["sabór","sábor"],cat:"AGUDA",syl:"sa-bor",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"valor",ok:"valor",d:["valór","válor"],cat:"AGUDA",syl:"va-lor",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"pintor",ok:"pintor",d:["pintór","píntor"],cat:"AGUDA",syl:"pin-tor",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"doctor",ok:"doctor",d:["doctór","dóctor"],cat:"AGUDA",syl:"doc-tor",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"temblor",ok:"temblor",d:["temblór","témblor"],cat:"AGUDA",syl:"tem-blor",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"amistad",ok:"amistad",d:["amistád","amístad"],cat:"AGUDA",syl:"a-mis-tad",nota:"(Es aguda y termina en «d», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"libertad",ok:"libertad",d:["libertád","libértad"],cat:"AGUDA",syl:"li-ber-tad",nota:"(Es aguda y termina en «d», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"salud",ok:"salud",d:["salúd","sálud"],cat:"AGUDA",syl:"sa-lud",nota:"(Es aguda y termina en «d», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"juventud",ok:"juventud",d:["juventúd","juvéntud"],cat:"AGUDA",syl:"ju-ven-tud",nota:"(Es aguda y termina en «d», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"capaz",ok:"capaz",d:["capáz","cápaz"],cat:"AGUDA",syl:"ca-paz",nota:"(Es aguda y termina en «z», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"antifaz",ok:"antifaz",d:["antifáz","antífaz"],cat:"AGUDA",syl:"an-ti-faz",nota:"(Es aguda y termina en «z», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"disfraz",ok:"disfraz",d:["disfráz","dísfraz"],cat:"AGUDA",syl:"dis-fraz",nota:"(Es aguda y termina en «z», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"veloz",ok:"veloz",d:["velóz","véloz"],cat:"AGUDA",syl:"ve-loz",nota:"(Es aguda y termina en «z», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"feroz",ok:"feroz",d:["feróz","féroz"],cat:"AGUDA",syl:"fe-roz",nota:"(Es aguda y termina en «z», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"arroz",ok:"arroz",d:["arróz","árroz"],cat:"AGUDA",syl:"a-rroz",nota:"(Es aguda y termina en «z», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"lombriz",ok:"lombriz",d:["lombríz","lómbriz"],cat:"AGUDA",syl:"lom-briz",nota:"(Es aguda y termina en «z», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"actriz",ok:"actriz",d:["actríz","áctriz"],cat:"AGUDA",syl:"ac-triz",nota:"(Es aguda y termina en «z», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"bondad",ok:"bondad",d:["bondád","bóndad"],cat:"AGUDA",syl:"bon-dad",nota:"(Es aguda y termina en «d», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"unidad",ok:"unidad",d:["unidád","unídad"],cat:"AGUDA",syl:"u-ni-dad",nota:"(Es aguda y termina en «d», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"calidad",ok:"calidad",d:["calidád","calídad"],cat:"AGUDA",syl:"ca-li-dad",nota:"(Es aguda y termina en «d», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"compas",ok:"compás",d:["compas","cómpas"],cat:"AGUDA",syl:"com-pás"},
  {p:"autobus",ok:"autobús",d:["autobus","autóbus"],cat:"AGUDA",syl:"au-to-bús"},
  {p:"volcan",ok:"volcán",d:["volcan","vólcan"],cat:"AGUDA",syl:"vol-cán"},
  {p:"huracan",ok:"huracán",d:["huracan","hurácan"],cat:"AGUDA",syl:"hu-ra-cán"},
  {p:"tapon",ok:"tapón",d:["tapon","tápon"],cat:"AGUDA",syl:"ta-pón"},
  {p:"salon",ok:"salón",d:["salon","sálon"],cat:"AGUDA",syl:"sa-lón"},
  {p:"tazon",ok:"tazón",d:["tazon","tázon"],cat:"AGUDA",syl:"ta-zón"},
  {p:"baston",ok:"bastón",d:["baston","báston"],cat:"AGUDA",syl:"bas-tón"},
  {p:"version",ok:"versión",d:["version","vérsion"],cat:"AGUDA",syl:"ver-sión"},
  {p:"mision",ok:"misión",d:["mision","mísion"],cat:"AGUDA",syl:"mi-sión"},
  {p:"region",ok:"región",d:["region","région"],cat:"AGUDA",syl:"re-gión"},
  {p:"religion",ok:"religión",d:["religion","relígion"],cat:"AGUDA",syl:"re-li-gión"},
  {p:"direccion",ok:"dirección",d:["direccion","diréccion"],cat:"AGUDA",syl:"di-rec-ción"},
  {p:"confusion",ok:"confusión",d:["confusion","confúsion"],cat:"AGUDA",syl:"con-fu-sión"},
  {p:"informacion",ok:"información",d:["informacion","informácion"],cat:"AGUDA",syl:"in-for-ma-ción"},
  {p:"educacion",ok:"educación",d:["educacion","educácion"],cat:"AGUDA",syl:"e-du-ca-ción"},
  {p:"capitan",ok:"capitán",d:["capitan","capítan"],cat:"AGUDA",syl:"ca-pi-tán"},
  {p:"aleman",ok:"alemán",d:["aleman","aléman"],cat:"AGUDA",syl:"a-le-mán"},
  {p:"chapulin",ok:"chapulín",d:["chapulin","chapúlin"],cat:"AGUDA",syl:"cha-pu-lín"},
  {p:"comal",ok:"comal",d:["comál","cómal"],cat:"AGUDA",syl:"co-mal",nota:"(Es aguda y termina en «l», no en N, S ni vocal: por eso NO lleva tilde.)"},
  {p:"arbol",ok:"árbol",d:["arbol","arból"],cat:"LLANA",syl:"ár-bol"},
  {p:"lapiz",ok:"lápiz",d:["lapiz","lapíz"],cat:"LLANA",syl:"lá-piz"},
  {p:"azucar",ok:"azúcar",d:["azucar","azucár"],cat:"LLANA",syl:"a-zú-car"},
  {p:"facil",ok:"fácil",d:["facil","facíl"],cat:"LLANA",syl:"fá-cil"},
  {p:"dificil",ok:"difícil",d:["dificil","dificíl"],cat:"LLANA",syl:"di-fí-cil"},
  {p:"carcel",ok:"cárcel",d:["carcel","carcél"],cat:"LLANA",syl:"cár-cel"},
  {p:"cesped",ok:"césped",d:["cesped","cespéd"],cat:"LLANA",syl:"cés-ped"},
  {p:"album",ok:"álbum",d:["album","albúm"],cat:"LLANA",syl:"ál-bum"},
  {p:"movil",ok:"móvil",d:["movil","movíl"],cat:"LLANA",syl:"mó-vil"},
  {p:"util",ok:"útil",d:["util","utíl"],cat:"LLANA",syl:"ú-til"},
  {p:"docil",ok:"dócil",d:["docil","docíl"],cat:"LLANA",syl:"dó-cil"},
  {p:"cadaver",ok:"cadáver",d:["cadaver","cadavér"],cat:"LLANA",syl:"ca-dá-ver"},
  {p:"futbol",ok:"fútbol",d:["futbol","futból"],cat:"LLANA",syl:"fút-bol"},
  {p:"ambar",ok:"ámbar",d:["ambar","ambár"],cat:"LLANA",syl:"ám-bar"},
  {p:"almibar",ok:"almíbar",d:["almibar","almibár"],cat:"LLANA",syl:"al-mí-bar"},
  {p:"debil",ok:"débil",d:["debil","debíl"],cat:"LLANA",syl:"dé-bil"},
  {p:"habil",ok:"hábil",d:["habil","habíl"],cat:"LLANA",syl:"há-bil"},
  {p:"lider",ok:"líder",d:["lider","lidér"],cat:"LLANA",syl:"lí-der"},
  {p:"nacar",ok:"nácar",d:["nacar","nacár"],cat:"LLANA",syl:"ná-car"},
  {p:"mesa",ok:"mesa",d:["mésa","mesá"],cat:"LLANA",syl:"me-sa",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"casa",ok:"casa",d:["cása","casá"],cat:"LLANA",syl:"ca-sa",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"pupitre",ok:"pupitre",d:["pupítre","pupitré"],cat:"LLANA",syl:"pu-pi-tre",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"zapato",ok:"zapato",d:["zapáto","zapató"],cat:"LLANA",syl:"za-pa-to",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"camisa",ok:"camisa",d:["camísa","camisá"],cat:"LLANA",syl:"ca-mi-sa",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"ventana",ok:"ventana",d:["ventána","ventaná"],cat:"LLANA",syl:"ven-ta-na",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"joven",ok:"joven",d:["jóven","jovén"],cat:"LLANA",syl:"jo-ven",nota:"(Es grave y termina en «n»: por eso NO lleva tilde.)"},
  {p:"examen",ok:"examen",d:["exámen","examén"],cat:"LLANA",syl:"e-xa-men",nota:"(Es grave y termina en «n»: por eso NO lleva tilde.)"},
  {p:"crisis",ok:"crisis",d:["crísis","crisís"],cat:"LLANA",syl:"cri-sis",nota:"(Es grave y termina en «s»: por eso NO lleva tilde.)"},
  {p:"perro",ok:"perro",d:["pérro","perró"],cat:"LLANA",syl:"pe-rro",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"calle",ok:"calle",d:["cálle","callé"],cat:"LLANA",syl:"ca-lle",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"playa",ok:"playa",d:["pláya","playá"],cat:"LLANA",syl:"pla-ya",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"guitarra",ok:"guitarra",d:["guitárra","guitarrá"],cat:"LLANA",syl:"gui-ta-rra",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"lunes",ok:"lunes",d:["lúnes","lunés"],cat:"LLANA",syl:"lu-nes",nota:"(Es grave y termina en «s»: por eso NO lleva tilde.)"},
  {p:"queso",ok:"queso",d:["quéso","quesó"],cat:"LLANA",syl:"que-so",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"martes",ok:"martes",d:["mártes","martés"],cat:"LLANA",syl:"mar-tes",nota:"(Es grave y termina en «s»: por eso NO lleva tilde.)"},
  {p:"orden",ok:"orden",d:["órden","ordén"],cat:"LLANA",syl:"or-den",nota:"(Es grave y termina en «n»: por eso NO lleva tilde.)"},
  {p:"escuela",ok:"escuela",d:["escuéla","escuelá"],cat:"LLANA",syl:"es-cue-la",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"agil",ok:"ágil",d:["agil","agíl"],cat:"LLANA",syl:"á-gil"},
  {p:"fragil",ok:"frágil",d:["fragil","fragíl"],cat:"LLANA",syl:"frá-gil"},
  {p:"portatil",ok:"portátil",d:["portatil","portatíl"],cat:"LLANA",syl:"por-tá-til"},
  {p:"versatil",ok:"versátil",d:["versatil","versatíl"],cat:"LLANA",syl:"ver-sá-til"},
  {p:"fertil",ok:"fértil",d:["fertil","fertíl"],cat:"LLANA",syl:"fér-til"},
  {p:"esteril",ok:"estéril",d:["esteril","esteríl"],cat:"LLANA",syl:"es-té-ril"},
  {p:"fosil",ok:"fósil",d:["fosil","fosíl"],cat:"LLANA",syl:"fó-sil"},
  {p:"tunel",ok:"túnel",d:["tunel","tunél"],cat:"LLANA",syl:"tú-nel"},
  {p:"caracter",ok:"carácter",d:["caracter","caractér"],cat:"LLANA",syl:"ca-rác-ter"},
  {p:"condor",ok:"cóndor",d:["condor","condór"],cat:"LLANA",syl:"cón-dor"},
  {p:"angel",ok:"ángel",d:["angel","angél"],cat:"LLANA",syl:"án-gel"},
  {p:"apostol",ok:"apóstol",d:["apostol","apostól"],cat:"LLANA",syl:"a-pós-tol"},
  {p:"canibal",ok:"caníbal",d:["canibal","canibál"],cat:"LLANA",syl:"ca-ní-bal"},
  {p:"huesped",ok:"huésped",d:["huesped","huespéd"],cat:"LLANA",syl:"hués-ped"},
  {p:"dolar",ok:"dólar",d:["dolar","dolár"],cat:"LLANA",syl:"dó-lar"},
  {p:"laser",ok:"láser",d:["laser","lasér"],cat:"LLANA",syl:"lá-ser"},
  {p:"caliz",ok:"cáliz",d:["caliz","calíz"],cat:"LLANA",syl:"cá-liz"},
  {p:"torax",ok:"tórax",d:["torax","toráx"],cat:"LLANA",syl:"tó-rax"},
  {p:"onix",ok:"ónix",d:["onix","oníx"],cat:"LLANA",syl:"ó-nix"},
  {p:"fenix",ok:"fénix",d:["fenix","feníx"],cat:"LLANA",syl:"fé-nix"},
  {p:"crater",ok:"cráter",d:["crater","cratér"],cat:"LLANA",syl:"crá-ter"},
  {p:"sueter",ok:"suéter",d:["sueter","suetér"],cat:"LLANA",syl:"sué-ter"},
  {p:"femur",ok:"fémur",d:["femur","femúr"],cat:"LLANA",syl:"fé-mur"},
  {p:"martir",ok:"mártir",d:["martir","martír"],cat:"LLANA",syl:"már-tir"},
  {p:"marmol",ok:"mármol",d:["marmol","marmól"],cat:"LLANA",syl:"már-mol"},
  {p:"cuaderno",ok:"cuaderno",d:["cuadérno","cuadernó"],cat:"LLANA",syl:"cua-der-no",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"mochila",ok:"mochila",d:["mochíla","mochilá"],cat:"LLANA",syl:"mo-chi-la",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"libreta",ok:"libreta",d:["libréta","libretá"],cat:"LLANA",syl:"li-bre-ta",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"tijeras",ok:"tijeras",d:["tijéras","tijerás"],cat:"LLANA",syl:"ti-je-ras",nota:"(Es grave y termina en «s»: por eso NO lleva tilde.)"},
  {p:"horizonte",ok:"horizonte",d:["horizónte","horizonté"],cat:"LLANA",syl:"ho-ri-zon-te",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"montaña",ok:"montaña",d:["montáña","montañá"],cat:"LLANA",syl:"mon-ta-ña",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"planeta",ok:"planeta",d:["planéta","planetá"],cat:"LLANA",syl:"pla-ne-ta",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"amigo",ok:"amigo",d:["amígo","amigó"],cat:"LLANA",syl:"a-mi-go",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"familia",ok:"familia",d:["família","familiá"],cat:"LLANA",syl:"fa-mi-lia",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"carro",ok:"carro",d:["cárro","carró"],cat:"LLANA",syl:"ca-rro",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"bicicleta",ok:"bicicleta",d:["bicicléta","bicicletá"],cat:"LLANA",syl:"bi-ci-cle-ta",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"paraguas",ok:"paraguas",d:["paráguas","paraguás"],cat:"LLANA",syl:"pa-ra-guas",nota:"(Es grave y termina en «s»: por eso NO lleva tilde.)"},
  {p:"origen",ok:"origen",d:["orígen","origén"],cat:"LLANA",syl:"o-ri-gen",nota:"(Es grave y termina en «n»: por eso NO lleva tilde.)"},
  {p:"imagen",ok:"imagen",d:["imágen","imagén"],cat:"LLANA",syl:"i-ma-gen",nota:"(Es grave y termina en «n»: por eso NO lleva tilde.)"},
  {p:"volumen",ok:"volumen",d:["volúmen","volumén"],cat:"LLANA",syl:"vo-lu-men",nota:"(Es grave y termina en «n»: por eso NO lleva tilde.)"},
  {p:"resumen",ok:"resumen",d:["resúmen","resumén"],cat:"LLANA",syl:"re-su-men",nota:"(Es grave y termina en «n»: por eso NO lleva tilde.)"},
  {p:"crimen",ok:"crimen",d:["crímen","crimén"],cat:"LLANA",syl:"cri-men",nota:"(Es grave y termina en «n»: por eso NO lleva tilde.)"},
  {p:"margen",ok:"margen",d:["márgen","margén"],cat:"LLANA",syl:"mar-gen",nota:"(Es grave y termina en «n»: por eso NO lleva tilde.)"},
  {p:"jueves",ok:"jueves",d:["juéves","juevés"],cat:"LLANA",syl:"jue-ves",nota:"(Es grave y termina en «s»: por eso NO lleva tilde.)"},
  {p:"viernes",ok:"viernes",d:["viérnes","viernés"],cat:"LLANA",syl:"vier-nes",nota:"(Es grave y termina en «s»: por eso NO lleva tilde.)"},
  {p:"pelota",ok:"pelota",d:["pelóta","pelotá"],cat:"LLANA",syl:"pe-lo-ta",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"globo",ok:"globo",d:["glóbo","globó"],cat:"LLANA",syl:"glo-bo",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"payaso",ok:"payaso",d:["payáso","payasó"],cat:"LLANA",syl:"pa-ya-so",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"tortilla",ok:"tortilla",d:["tortílla","tortillá"],cat:"LLANA",syl:"tor-ti-lla",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"frijoles",ok:"frijoles",d:["frijóles","frijolés"],cat:"LLANA",syl:"fri-jo-les",nota:"(Es grave y termina en «s»: por eso NO lleva tilde.)"},
  {p:"tacos",ok:"tacos",d:["tácos","tacós"],cat:"LLANA",syl:"ta-cos",nota:"(Es grave y termina en «s»: por eso NO lleva tilde.)"},
  {p:"salsa",ok:"salsa",d:["sálsa","salsá"],cat:"LLANA",syl:"sal-sa",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"llave",ok:"llave",d:["lláve","llavé"],cat:"LLANA",syl:"lla-ve",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"maestra",ok:"maestra",d:["maéstra","maestrá"],cat:"LLANA",syl:"ma-es-tra",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"cocina",ok:"cocina",d:["cocína","cociná"],cat:"LLANA",syl:"co-ci-na",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"caramelo",ok:"caramelo",d:["caramélo","carameló"],cat:"LLANA",syl:"ca-ra-me-lo",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"galleta",ok:"galleta",d:["galléta","galletá"],cat:"LLANA",syl:"ga-lle-ta",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"manzana",ok:"manzana",d:["manzána","manzaná"],cat:"LLANA",syl:"man-za-na",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"naranja",ok:"naranja",d:["naránja","naranjá"],cat:"LLANA",syl:"na-ran-ja",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"elefante",ok:"elefante",d:["elefánte","elefanté"],cat:"LLANA",syl:"e-le-fan-te",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"jirafa",ok:"jirafa",d:["jiráfa","jirafá"],cat:"LLANA",syl:"ji-ra-fa",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"caballo",ok:"caballo",d:["cabállo","caballó"],cat:"LLANA",syl:"ca-ba-llo",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"mariposa",ok:"mariposa",d:["maripósa","mariposá"],cat:"LLANA",syl:"ma-ri-po-sa",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"culebra",ok:"culebra",d:["culébra","culebrá"],cat:"LLANA",syl:"cu-le-bra",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"tortuga",ok:"tortuga",d:["tortúga","tortugá"],cat:"LLANA",syl:"tor-tu-ga",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"conserje",ok:"conserje",d:["consérje","conserjé"],cat:"LLANA",syl:"con-ser-je",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"campana",ok:"campana",d:["campána","campaná"],cat:"LLANA",syl:"cam-pa-na",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"maleta",ok:"maleta",d:["maléta","maletá"],cat:"LLANA",syl:"ma-le-ta",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"camioneta",ok:"camioneta",d:["camionéta","camionetá"],cat:"LLANA",syl:"ca-mio-ne-ta",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"persona",ok:"persona",d:["persóna","personá"],cat:"LLANA",syl:"per-so-na",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"cabeza",ok:"cabeza",d:["cabéza","cabezá"],cat:"LLANA",syl:"ca-be-za",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"rodilla",ok:"rodilla",d:["rodílla","rodillá"],cat:"LLANA",syl:"ro-di-lla",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"oreja",ok:"oreja",d:["oréja","orejá"],cat:"LLANA",syl:"o-re-ja",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"espalda",ok:"espalda",d:["espálda","espaldá"],cat:"LLANA",syl:"es-pal-da",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"pintura",ok:"pintura",d:["pintúra","pinturá"],cat:"LLANA",syl:"pin-tu-ra",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"cultura",ok:"cultura",d:["cultúra","culturá"],cat:"LLANA",syl:"cul-tu-ra",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"ciencia",ok:"ciencia",d:["ciéncia","cienciá"],cat:"LLANA",syl:"cien-cia",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"historia",ok:"historia",d:["história","historiá"],cat:"LLANA",syl:"his-to-ria",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"lectura",ok:"lectura",d:["lectúra","lecturá"],cat:"LLANA",syl:"lec-tu-ra",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"escritura",ok:"escritura",d:["escritúra","escriturá"],cat:"LLANA",syl:"es-cri-tu-ra",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"aventura",ok:"aventura",d:["aventúra","aventurá"],cat:"LLANA",syl:"a-ven-tu-ra",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"nube",ok:"nube",d:["núbe","nubé"],cat:"LLANA",syl:"nu-be",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"lluvia",ok:"lluvia",d:["llúvia","lluviá"],cat:"LLANA",syl:"llu-via",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"tormenta",ok:"tormenta",d:["torménta","tormentá"],cat:"LLANA",syl:"tor-men-ta",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"selva",ok:"selva",d:["sélva","selvá"],cat:"LLANA",syl:"sel-va",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"desierto",ok:"desierto",d:["desiérto","desiertó"],cat:"LLANA",syl:"de-sier-to",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"isla",ok:"isla",d:["ísla","islá"],cat:"LLANA",syl:"is-la",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"laguna",ok:"laguna",d:["lagúna","laguná"],cat:"LLANA",syl:"la-gu-na",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"verano",ok:"verano",d:["veráno","veranó"],cat:"LLANA",syl:"ve-ra-no",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"invierno",ok:"invierno",d:["inviérno","inviernó"],cat:"LLANA",syl:"in-vier-no",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"otoño",ok:"otoño",d:["otóño","otoñó"],cat:"LLANA",syl:"o-to-ño",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"primavera",ok:"primavera",d:["primavéra","primaverá"],cat:"LLANA",syl:"pri-ma-ve-ra",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.)"},
  {p:"musica",ok:"música",d:["musica","musíca"],cat:"ESDRUJULA",syl:"mú-si-ca"},
  {p:"telefono",ok:"teléfono",d:["telefono","telefóno"],cat:"ESDRUJULA",syl:"te-lé-fo-no"},
  {p:"quimica",ok:"química",d:["quimica","quimíca"],cat:"ESDRUJULA",syl:"quí-mi-ca"},
  {p:"lagrima",ok:"lágrima",d:["lagrima","lagríma"],cat:"ESDRUJULA",syl:"lá-gri-ma"},
  {p:"pajaro",ok:"pájaro",d:["pajaro","pajáro"],cat:"ESDRUJULA",syl:"pá-ja-ro"},
  {p:"boveda",ok:"bóveda",d:["boveda","bovéda"],cat:"ESDRUJULA",syl:"bó-ve-da"},
  {p:"pelicula",ok:"película",d:["pelicula","pelicúla"],cat:"ESDRUJULA",syl:"pe-lí-cu-la"},
  {p:"lampara",ok:"lámpara",d:["lampara","lampára"],cat:"ESDRUJULA",syl:"lám-pa-ra"},
  {p:"piramide",ok:"pirámide",d:["piramide","piramíde"],cat:"ESDRUJULA",syl:"pi-rá-mi-de"},
  {p:"murcielago",ok:"murciélago",d:["murcielago","murcielágo"],cat:"ESDRUJULA",syl:"mur-cié-la-go"},
  {p:"sabado",ok:"sábado",d:["sabado","sabádo"],cat:"ESDRUJULA",syl:"sá-ba-do"},
  {p:"miercoles",ok:"miércoles",d:["miercoles","miercóles"],cat:"ESDRUJULA",syl:"miér-co-les"},
  {p:"brujula",ok:"brújula",d:["brujula","brujúla"],cat:"ESDRUJULA",syl:"brú-ju-la"},
  {p:"platano",ok:"plátano",d:["platano","platáno"],cat:"ESDRUJULA",syl:"plá-ta-no"},
  {p:"rapido",ok:"rápido",d:["rapido","rapído"],cat:"ESDRUJULA",syl:"rá-pi-do"},
  {p:"camara",ok:"cámara",d:["camara","camára"],cat:"ESDRUJULA",syl:"cá-ma-ra"},
  {p:"unico",ok:"único",d:["unico","uníco"],cat:"ESDRUJULA",syl:"ú-ni-co"},
  {p:"silaba",ok:"sílaba",d:["silaba","silába"],cat:"ESDRUJULA",syl:"sí-la-ba"},
  {p:"metodo",ok:"método",d:["metodo","metódo"],cat:"ESDRUJULA",syl:"mé-to-do"},
  {p:"relampago",ok:"relámpago",d:["relampago","relampágo"],cat:"ESDRUJULA",syl:"re-lám-pa-go"},
  {p:"estomago",ok:"estómago",d:["estomago","estomágo"],cat:"ESDRUJULA",syl:"es-tó-ma-go"},
  {p:"angulo",ok:"ángulo",d:["angulo","angúlo"],cat:"ESDRUJULA",syl:"án-gu-lo"},
  {p:"lapices",ok:"lápices",d:["lapices","lapíces"],cat:"ESDRUJULA",syl:"lá-pi-ces"},
  {p:"jovenes",ok:"jóvenes",d:["jovenes","jovénes"],cat:"ESDRUJULA",syl:"jó-ve-nes"},
  {p:"examenes",ok:"exámenes",d:["examenes","examénes"],cat:"ESDRUJULA",syl:"e-xá-me-nes"},
  {p:"arboles",ok:"árboles",d:["arboles","arbóles"],cat:"ESDRUJULA",syl:"ár-bo-les"},
  {p:"matematicas",ok:"matemáticas",d:["matematicas","matematícas"],cat:"ESDRUJULA",syl:"ma-te-má-ti-cas"},
  {p:"cascara",ok:"cáscara",d:["cascara","cascára"],cat:"ESDRUJULA",syl:"cás-ca-ra"},
  {p:"globulo",ok:"glóbulo",d:["globulo","globúlo"],cat:"ESDRUJULA",syl:"gló-bu-lo"},
  {p:"espiritu",ok:"espíritu",d:["espiritu","espirítu"],cat:"ESDRUJULA",syl:"es-pí-ri-tu"},
  {p:"vehiculo",ok:"vehículo",d:["vehiculo","vehicúlo"],cat:"ESDRUJULA",syl:"ve-hí-cu-lo"},
  {p:"musico",ok:"músico",d:["musico","musíco"],cat:"ESDRUJULA",syl:"mú-si-co"},
  {p:"timido",ok:"tímido",d:["timido","timído"],cat:"ESDRUJULA",syl:"tí-mi-do"},
  {p:"palido",ok:"pálido",d:["palido","palído"],cat:"ESDRUJULA",syl:"pá-li-do"},
  {p:"microfono",ok:"micrófono",d:["microfono","microfóno"],cat:"ESDRUJULA",syl:"mi-cró-fo-no"},
  {p:"logico",ok:"lógico",d:["logico","logíco"],cat:"ESDRUJULA",syl:"ló-gi-co"},
  {p:"quimico",ok:"químico",d:["quimico","quimíco"],cat:"ESDRUJULA",syl:"quí-mi-co"},
  {p:"fisica",ok:"física",d:["fisica","fisíca"],cat:"ESDRUJULA",syl:"fí-si-ca"},
  {p:"historico",ok:"histórico",d:["historico","historíco"],cat:"ESDRUJULA",syl:"his-tó-ri-co"},
  {p:"magnetico",ok:"magnético",d:["magnetico","magnetíco"],cat:"ESDRUJULA",syl:"mag-né-ti-co"},
  {p:"electrico",ok:"eléctrico",d:["electrico","electríco"],cat:"ESDRUJULA",syl:"e-léc-tri-co"},
  {p:"simpatico",ok:"simpático",d:["simpatico","simpatíco"],cat:"ESDRUJULA",syl:"sim-pá-ti-co"},
  {p:"fantastico",ok:"fantástico",d:["fantastico","fantastíco"],cat:"ESDRUJULA",syl:"fan-tás-ti-co"},
  {p:"plastico",ok:"plástico",d:["plastico","plastíco"],cat:"ESDRUJULA",syl:"plás-ti-co"},
  {p:"credito",ok:"crédito",d:["credito","credíto"],cat:"ESDRUJULA",syl:"cré-di-to"},
  {p:"proximo",ok:"próximo",d:["proximo","proxímo"],cat:"ESDRUJULA",syl:"pró-xi-mo"},
  {p:"tipico",ok:"típico",d:["tipico","tipíco"],cat:"ESDRUJULA",syl:"tí-pi-co"},
  {p:"utiles",ok:"útiles",d:["utiles","utíles"],cat:"ESDRUJULA",syl:"ú-ti-les"},
  {p:"rafaga",ok:"ráfaga",d:["rafaga","rafága"],cat:"ESDRUJULA",syl:"rá-fa-ga"},
  {p:"merito",ok:"mérito",d:["merito","meríto"],cat:"ESDRUJULA",syl:"mé-ri-to"},
  {p:"aritmetica",ok:"aritmética",d:["aritmetica","aritmetíca"],cat:"ESDRUJULA",syl:"a-rit-mé-ti-ca"},
  {p:"biologo",ok:"biólogo",d:["biologo","biológo"],cat:"ESDRUJULA",syl:"bió-lo-go"},
  {p:"analisis",ok:"análisis",d:["analisis","analísis"],cat:"ESDRUJULA",syl:"a-ná-li-sis"},
  {p:"sintesis",ok:"síntesis",d:["sintesis","sintésis"],cat:"ESDRUJULA",syl:"sín-te-sis"},
  {p:"digame",ok:"dígame",d:["digame","digáme"],cat:"ESDRUJULA",syl:"dí-ga-me"},
  {p:"compralo",ok:"cómpralo",d:["compralo","comprálo"],cat:"ESDRUJULA",syl:"cóm-pra-lo"},
  {p:"guardalo",ok:"guárdalo",d:["guardalo","guardálo"],cat:"ESDRUJULA",syl:"guár-da-lo"},
  {p:"escribelo",ok:"escríbelo",d:["escribelo","escribélo"],cat:"ESDRUJULA",syl:"es-crí-be-lo"},
  {p:"aguila",ok:"águila",d:["aguila","aguíla"],cat:"ESDRUJULA",syl:"á-gui-la"},
  {p:"tortola",ok:"tórtola",d:["tortola","tortóla"],cat:"ESDRUJULA",syl:"tór-to-la"},
  {p:"solido",ok:"sólido",d:["solido","solído"],cat:"ESDRUJULA",syl:"só-li-do"},
  {p:"vibora",ok:"víbora",d:["vibora","vibóra"],cat:"ESDRUJULA",syl:"ví-bo-ra"},
  {p:"ceramica",ok:"cerámica",d:["ceramica","ceramíca"],cat:"ESDRUJULA",syl:"ce-rá-mi-ca"},
  {p:"kilometro",ok:"kilómetro",d:["kilometro","kilométro"],cat:"ESDRUJULA",syl:"ki-ló-me-tro"},
  {p:"centimetro",ok:"centímetro",d:["centimetro","centimétro"],cat:"ESDRUJULA",syl:"cen-tí-me-tro"},
  {p:"termometro",ok:"termómetro",d:["termometro","termométro"],cat:"ESDRUJULA",syl:"ter-mó-me-tro"},
  {p:"petalo",ok:"pétalo",d:["petalo","petálo"],cat:"ESDRUJULA",syl:"pé-ta-lo"},
  {p:"jicara",ok:"jícara",d:["jicara","jicára"],cat:"ESDRUJULA",syl:"jí-ca-ra"},
  {p:"periodico",ok:"periódico",d:["periodico","periodíco"],cat:"ESDRUJULA",syl:"pe-rió-di-co"},
  {p:"clasico",ok:"clásico",d:["clasico","clasíco"],cat:"ESDRUJULA",syl:"clá-si-co"},
  {p:"mamifero",ok:"mamífero",d:["mamifero","mamiféro"],cat:"ESDRUJULA",syl:"ma-mí-fe-ro"},
  {p:"heroe",ok:"héroe",d:["heroe","heróe"],cat:"ESDRUJULA",syl:"hé-ro-e"},
  {p:"matematico",ok:"matemático",d:["matematico","matematíco"],cat:"ESDRUJULA",syl:"ma-te-má-ti-co"},
  {p:"botanica",ok:"botánica",d:["botanica","botaníca"],cat:"ESDRUJULA",syl:"bo-tá-ni-ca"},
  {p:"mecanico",ok:"mecánico",d:["mecanico","mecaníco"],cat:"ESDRUJULA",syl:"me-cá-ni-co"},
  {p:"atomico",ok:"atómico",d:["atomico","atomíco"],cat:"ESDRUJULA",syl:"a-tó-mi-co"},
  {p:"caratula",ok:"carátula",d:["caratula","caratúla"],cat:"ESDRUJULA",syl:"ca-rá-tu-la"},
  {p:"toxico",ok:"tóxico",d:["toxico","toxíco"],cat:"ESDRUJULA",syl:"tó-xi-co"},
  {p:"subito",ok:"súbito",d:["subito","subíto"],cat:"ESDRUJULA",syl:"sú-bi-to"},
  {p:"indice",ok:"índice",d:["indice","indíce"],cat:"ESDRUJULA",syl:"ín-di-ce"},
  {p:"parpado",ok:"párpado",d:["parpado","parpádo"],cat:"ESDRUJULA",syl:"pár-pa-do"},
  {p:"codigo",ok:"código",d:["codigo","codígo"],cat:"ESDRUJULA",syl:"có-di-go"},
  {p:"poliza",ok:"póliza",d:["poliza","políza"],cat:"ESDRUJULA",syl:"pó-li-za"},
  {p:"acustica",ok:"acústica",d:["acustica","acustíca"],cat:"ESDRUJULA",syl:"a-cús-ti-ca"},
  {p:"comica",ok:"cómica",d:["comica","comíca"],cat:"ESDRUJULA",syl:"có-mi-ca"},
  {p:"decada",ok:"década",d:["decada","decáda"],cat:"ESDRUJULA",syl:"dé-ca-da"},
  {p:"digamelo",ok:"dígamelo",d:["digamelo","digámelo"],cat:"SOBRESDRUJULA",syl:"dí-ga-me-lo"},
  {p:"digaselo",ok:"dígaselo",d:["digaselo","digáselo"],cat:"SOBRESDRUJULA",syl:"dí-ga-se-lo"},
  {p:"explicamelo",ok:"explícamelo",d:["explicamelo","explicámelo"],cat:"SOBRESDRUJULA",syl:"ex-plí-ca-me-lo"},
  {p:"compraselo",ok:"cómpraselo",d:["compraselo","compráselo"],cat:"SOBRESDRUJULA",syl:"cóm-pra-se-lo"},
  {p:"cuentamelo",ok:"cuéntamelo",d:["cuentamelo","cuentámelo"],cat:"SOBRESDRUJULA",syl:"cuén-ta-me-lo"},
  {p:"regalaselo",ok:"regálaselo",d:["regalaselo","regaláselo"],cat:"SOBRESDRUJULA",syl:"re-gá-la-se-lo"},
  {p:"prestamelo",ok:"préstamelo",d:["prestamelo","prestámelo"],cat:"SOBRESDRUJULA",syl:"prés-ta-me-lo"},
  {p:"cometelo",ok:"cómetelo",d:["cometelo","comételo"],cat:"SOBRESDRUJULA",syl:"có-me-te-lo"},
  {p:"guardamelo",ok:"guárdamelo",d:["guardamelo","guardámelo"],cat:"SOBRESDRUJULA",syl:"guár-da-me-lo"},
  {p:"devuelvemelo",ok:"devuélvemelo",d:["devuelvemelo","devuelvémelo"],cat:"SOBRESDRUJULA",syl:"de-vuél-ve-me-lo"},
  {p:"llevatelo",ok:"llévatelo",d:["llevatelo","llevátelo"],cat:"SOBRESDRUJULA",syl:"llé-va-te-lo"},
  {p:"entregaselo",ok:"entrégaselo",d:["entregaselo","entregáselo"],cat:"SOBRESDRUJULA",syl:"en-tré-ga-se-lo"},
  {p:"escribemelo",ok:"escríbemelo",d:["escribemelo","escribémelo"],cat:"SOBRESDRUJULA",syl:"es-crí-be-me-lo"},
  {p:"muestramelo",ok:"muéstramelo",d:["muestramelo","muestrámelo"],cat:"SOBRESDRUJULA",syl:"mués-tra-me-lo"},
  {p:"apuntatelo",ok:"apúntatelo",d:["apuntatelo","apuntátelo"],cat:"SOBRESDRUJULA",syl:"a-pún-ta-te-lo"},
  {p:"mandamelo",ok:"mándamelo",d:["mandamelo","mandámelo"],cat:"SOBRESDRUJULA",syl:"mán-da-me-lo"},
  {p:"pasamelo",ok:"pásamelo",d:["pasamelo","pasámelo"],cat:"SOBRESDRUJULA",syl:"pá-sa-me-lo"},
  {p:"traemelo",ok:"tráemelo",d:["traemelo","traémelo"],cat:"SOBRESDRUJULA",syl:"trá-e-me-lo"},
  {p:"leemelo",ok:"léemelo",d:["leemelo","leémelo"],cat:"SOBRESDRUJULA",syl:"lé-e-me-lo"},
  {p:"cometela",ok:"cómetela",d:["cometela","cométela"],cat:"SOBRESDRUJULA",syl:"có-me-te-la"},
  {p:"bebetelo",ok:"bébetelo",d:["bebetelo","bebételo"],cat:"SOBRESDRUJULA",syl:"bé-be-te-lo"},
  {p:"pideselo",ok:"pídeselo",d:["pideselo","pidéselo"],cat:"SOBRESDRUJULA",syl:"pí-de-se-lo"},
  {p:"digasela",ok:"dígasela",d:["digasela","digásela"],cat:"SOBRESDRUJULA",syl:"dí-ga-se-la"},
  {p:"llevaselo",ok:"llévaselo",d:["llevaselo","lleváselo"],cat:"SOBRESDRUJULA",syl:"llé-va-se-lo"},
  {p:"quitatelo",ok:"quítatelo",d:["quitatelo","quitátelo"],cat:"SOBRESDRUJULA",syl:"quí-ta-te-lo"},
  {p:"acercamelo",ok:"acércamelo",d:["acercamelo","acercámelo"],cat:"SOBRESDRUJULA",syl:"a-cér-ca-me-lo"},
  {p:"enseñamelo",ok:"enséñamelo",d:["enseñamelo","enseñámelo"],cat:"SOBRESDRUJULA",syl:"en-sé-ña-me-lo"},
  {p:"repitemelo",ok:"repítemelo",d:["repitemelo","repitémelo"],cat:"SOBRESDRUJULA",syl:"re-pí-te-me-lo"},
  {p:"explicanoslo",ok:"explícanoslo",d:["explicanoslo","explicánoslo"],cat:"SOBRESDRUJULA",syl:"ex-plí-ca-nos-lo"},
  {p:"avisamelo",ok:"avísamelo",d:["avisamelo","avisámelo"],cat:"SOBRESDRUJULA",syl:"a-ví-sa-me-lo"},
  {p:"cuidamelo",ok:"cuídamelo",d:["cuidamelo","cuidámelo"],cat:"SOBRESDRUJULA",syl:"cuí-da-me-lo"},
  {p:"guardaselo",ok:"guárdaselo",d:["guardaselo","guardáselo"],cat:"SOBRESDRUJULA",syl:"guár-da-se-lo"},
  {p:"cantasela",ok:"cántasela",d:["cantasela","cantásela"],cat:"SOBRESDRUJULA",syl:"cán-ta-se-la"},
  {p:"dibujamelo",ok:"dibújamelo",d:["dibujamelo","dibujámelo"],cat:"SOBRESDRUJULA",syl:"di-bú-ja-me-lo"},
  {p:"escuchamelo",ok:"escúchamelo",d:["escuchamelo","escuchámelo"],cat:"SOBRESDRUJULA",syl:"es-cú-cha-me-lo"},
  {p:"buscamelo",ok:"búscamelo",d:["buscamelo","buscámelo"],cat:"SOBRESDRUJULA",syl:"bús-ca-me-lo"},
  {p:"firmamelo",ok:"fírmamelo",d:["firmamelo","firmámelo"],cat:"SOBRESDRUJULA",syl:"fír-ma-me-lo"},
  {p:"regalamelo",ok:"regálamelo",d:["regalamelo","regalámelo"],cat:"SOBRESDRUJULA",syl:"re-gá-la-me-lo"},
  {p:"lavatelas",ok:"lávatelas",d:["lavatelas","lavátelas"],cat:"SOBRESDRUJULA",syl:"lá-va-te-las"},
  {p:"pintamelo",ok:"píntamelo",d:["pintamelo","pintámelo"],cat:"SOBRESDRUJULA",syl:"pín-ta-me-lo"},
  {p:"arreglamelo",ok:"arréglamelo",d:["arreglamelo","arreglámelo"],cat:"SOBRESDRUJULA",syl:"a-rré-gla-me-lo"},
  {p:"dia",ok:"día",d:["dia","diá"],cat:"HIATO",syl:"dí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"sonrie",ok:"sonríe",d:["sonrie","sonrié"],cat:"HIATO",syl:"son-rí-e",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"tia",ok:"tía",d:["tia","tiá"],cat:"HIATO",syl:"tí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"maiz",ok:"maíz",d:["maiz","máiz"],cat:"HIATO",syl:"ma-íz",nota:"(La regla de las agudas diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"raiz",ok:"raíz",d:["raiz","ráiz"],cat:"HIATO",syl:"ra-íz",nota:"(La regla de las agudas diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"baul",ok:"baúl",d:["baul","bául"],cat:"HIATO",syl:"ba-úl",nota:"(La regla de las agudas diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"reir",ok:"reír",d:["reir","réir"],cat:"HIATO",syl:"re-ír",nota:"(La regla de las agudas diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"oir",ok:"oír",d:["oir","óir"],cat:"HIATO",syl:"o-ír",nota:"(La regla de las agudas diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"leido",ok:"leído",d:["leido","leidó"],cat:"HIATO",syl:"le-í-do",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"oido",ok:"oído",d:["oido","oidó"],cat:"HIATO",syl:"o-í-do",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"caida",ok:"caída",d:["caida","caidá"],cat:"HIATO",syl:"ca-í-da",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"grua",ok:"grúa",d:["grua","gruá"],cat:"HIATO",syl:"grú-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"actua",ok:"actúa",d:["actua","actuá"],cat:"HIATO",syl:"ac-tú-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"reune",ok:"reúne",d:["reune","reuné"],cat:"HIATO",syl:"re-ú-ne",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"policia",ok:"policía",d:["policia","policiá"],cat:"HIATO",syl:"po-li-cí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"bateria",ok:"batería",d:["bateria","bateriá"],cat:"HIATO",syl:"ba-te-rí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"panaderia",ok:"panadería",d:["panaderia","panaderiá"],cat:"HIATO",syl:"pa-na-de-rí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"prohibe",ok:"prohíbe",d:["prohibe","prohibé"],cat:"HIATO",syl:"pro-hí-be",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"buho",ok:"búho",d:["buho","buhó"],cat:"HIATO",syl:"bú-ho",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"pais",ok:"país",d:["pais","páis"],cat:"AGUDA",syl:"pa-ís",nota:"(Tiene hiato: sus vocales juntas van en sílabas distintas.)"},
  {p:"leon",ok:"león",d:["leon","léon"],cat:"AGUDA",syl:"le-ón",nota:"(Tiene hiato: sus vocales juntas van en sílabas distintas.)"},
  {p:"poeta",ok:"poeta",d:["poéta","poetá"],cat:"LLANA",syl:"po-e-ta",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.) (Tiene hiato: sus vocales juntas van en sílabas distintas.)"},
  {p:"caer",ok:"caer",d:["caér","cáer"],cat:"AGUDA",syl:"ca-er",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.) (Tiene hiato: sus vocales juntas van en sílabas distintas.)"},
  {p:"teatro",ok:"teatro",d:["teátro","teatró"],cat:"LLANA",syl:"te-a-tro",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.) (Tiene hiato: sus vocales juntas van en sílabas distintas.)"},
  {p:"aereo",ok:"aéreo",d:["aereo","aeréo"],cat:"ESDRUJULA",syl:"a-é-re-o",nota:"(Tiene hiato: sus vocales juntas van en sílabas distintas.)"},
  {p:"peor",ok:"peor",d:["peór","péor"],cat:"AGUDA",syl:"pe-or",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.) (Tiene hiato: sus vocales juntas van en sílabas distintas.)"},
  {p:"maestro",ok:"maestro",d:["maéstro","maestró"],cat:"LLANA",syl:"ma-es-tro",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.) (Tiene hiato: sus vocales juntas van en sílabas distintas.)"},
  {p:"energia",ok:"energía",d:["energia","energiá"],cat:"HIATO",syl:"e-ner-gí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"alegria",ok:"alegría",d:["alegria","alegriá"],cat:"HIATO",syl:"a-le-grí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"geografia",ok:"geografía",d:["geografia","geografiá"],cat:"HIATO",syl:"ge-o-gra-fí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"biologia",ok:"biología",d:["biologia","biologiá"],cat:"HIATO",syl:"bio-lo-gí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"alcaldia",ok:"alcaldía",d:["alcaldia","alcaldiá"],cat:"HIATO",syl:"al-cal-dí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"cafeteria",ok:"cafetería",d:["cafeteria","cafeteriá"],cat:"HIATO",syl:"ca-fe-te-rí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"zapateria",ok:"zapatería",d:["zapateria","zapateriá"],cat:"HIATO",syl:"za-pa-te-rí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"papeleria",ok:"papelería",d:["papeleria","papeleriá"],cat:"HIATO",syl:"pa-pe-le-rí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"libreria",ok:"librería",d:["libreria","libreriá"],cat:"HIATO",syl:"li-bre-rí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"pasteleria",ok:"pastelería",d:["pasteleria","pasteleriá"],cat:"HIATO",syl:"pas-te-le-rí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"tortilleria",ok:"tortillería",d:["tortilleria","tortilleriá"],cat:"HIATO",syl:"tor-ti-lle-rí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"fria",ok:"fría",d:["fria","friá"],cat:"HIATO",syl:"frí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"habia",ok:"había",d:["habia","habiá"],cat:"HIATO",syl:"ha-bí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"decia",ok:"decía",d:["decia","deciá"],cat:"HIATO",syl:"de-cí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"vivia",ok:"vivía",d:["vivia","viviá"],cat:"HIATO",syl:"vi-ví-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"comia",ok:"comía",d:["comia","comiá"],cat:"HIATO",syl:"co-mí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"ataud",ok:"ataúd",d:["ataud","atáud"],cat:"HIATO",syl:"a-ta-úd",nota:"(La regla de las agudas diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"bahia",ok:"bahía",d:["bahia","bahiá"],cat:"HIATO",syl:"ba-hí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"pua",ok:"púa",d:["pua","puá"],cat:"HIATO",syl:"pú-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"caido",ok:"caído",d:["caido","caidó"],cat:"HIATO",syl:"ca-í-do",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"leiste",ok:"leíste",d:["leiste","leisté"],cat:"HIATO",syl:"le-ís-te",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"oimos",ok:"oímos",d:["oimos","oimós"],cat:"HIATO",syl:"o-í-mos",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"evalua",ok:"evalúa",d:["evalua","evaluá"],cat:"HIATO",syl:"e-va-lú-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"gradua",ok:"gradúa",d:["gradua","graduá"],cat:"HIATO",syl:"gra-dú-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"travesia",ok:"travesía",d:["travesia","travesiá"],cat:"HIATO",syl:"tra-ve-sí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"melodia",ok:"melodía",d:["melodia","melodiá"],cat:"HIATO",syl:"me-lo-dí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"armonia",ok:"armonía",d:["armonia","armoniá"],cat:"HIATO",syl:"ar-mo-ní-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"fantasia",ok:"fantasía",d:["fantasia","fantasiá"],cat:"HIATO",syl:"fan-ta-sí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"poesia",ok:"poesía",d:["poesia","poesiá"],cat:"HIATO",syl:"po-e-sí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"canoa",ok:"canoa",d:["canóa","canoá"],cat:"LLANA",syl:"ca-no-a",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.) (Tiene hiato: sus vocales juntas van en sílabas distintas.)"},
  {p:"idea",ok:"idea",d:["idéa","ideá"],cat:"LLANA",syl:"i-de-a",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.) (Tiene hiato: sus vocales juntas van en sílabas distintas.)"},
  {p:"cacao",ok:"cacao",d:["cacáo","cacaó"],cat:"LLANA",syl:"ca-ca-o",nota:"(Es grave y termina en vocal: por eso NO lleva tilde.) (Tiene hiato: sus vocales juntas van en sílabas distintas.)"},
  {p:"pelear",ok:"pelear",d:["peleár","peléar"],cat:"AGUDA",syl:"pe-le-ar",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.) (Tiene hiato: sus vocales juntas van en sílabas distintas.)"},
  {p:"creer",ok:"creer",d:["creér","créer"],cat:"AGUDA",syl:"cre-er",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.) (Tiene hiato: sus vocales juntas van en sílabas distintas.)"},
  {p:"leer",ok:"leer",d:["leér","léer"],cat:"AGUDA",syl:"le-er",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.) (Tiene hiato: sus vocales juntas van en sílabas distintas.)"},
  {p:"traer",ok:"traer",d:["traér","tráer"],cat:"AGUDA",syl:"tra-er",nota:"(Es aguda y termina en «r», no en N, S ni vocal: por eso NO lleva tilde.) (Tiene hiato: sus vocales juntas van en sílabas distintas.)"},
  {p:"oceano",ok:"océano",d:["oceano","oceáno"],cat:"ESDRUJULA",syl:"o-cé-a-no",nota:"(Tiene hiato: sus vocales juntas van en sílabas distintas.)"},
  {p:"ahi",ok:"ahí",d:["ahi","áhi"],cat:"AGUDA",syl:"a-hí",nota:"(Tiene hiato: sus vocales juntas van en sílabas distintas.)"},
  {p:"reimos",ok:"reímos",d:["reimos","reimós"],cat:"HIATO",syl:"re-í-mos",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"sonreir",ok:"sonreír",d:["sonreir","sonréir"],cat:"HIATO",syl:"son-re-ír",nota:"(La regla de las agudas diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"oia",ok:"oía",d:["oia","oiá"],cat:"HIATO",syl:"o-í-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"leia",ok:"leía",d:["leia","leiá"],cat:"HIATO",syl:"le-í-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"traia",ok:"traía",d:["traia","traiá"],cat:"HIATO",syl:"tra-í-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"caia",ok:"caía",d:["caia","caiá"],cat:"HIATO",syl:"ca-í-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"mania",ok:"manía",d:["mania","maniá"],cat:"HIATO",syl:"ma-ní-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"tio",ok:"tío",d:["tio","tió"],cat:"HIATO",syl:"tí-o",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"mio",ok:"mío",d:["mio","mió"],cat:"HIATO",syl:"mí-o",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"sabiduria",ok:"sabiduría",d:["sabiduria","sabiduriá"],cat:"HIATO",syl:"sa-bi-du-rí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"cortesia",ok:"cortesía",d:["cortesia","cortesiá"],cat:"HIATO",syl:"cor-te-sí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"bujia",ok:"bujía",d:["bujia","bujiá"],cat:"HIATO",syl:"bu-jí-a",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"aulla",ok:"aúlla",d:["aulla","aullá"],cat:"HIATO",syl:"a-ú-lla",nota:"(La regla de las graves diría que no lleva tilde, pero el hiato acentual la obliga.)"},
  {p:"… eres el siguiente en pasar.",ok:"Tú",d:["Tu"],cat:"DIACRITICA",nota:"Aquí es pronombre: la persona (tú cantas)."},
  {p:"¿Ya trajiste … cuaderno?",ok:"tu",d:["tú"],cat:"DIACRITICA",nota:"Aquí es posesivo: lo que es tuyo (tu casa)."},
  {p:"¿Vienes … al partido?",ok:"tú",d:["tu"],cat:"DIACRITICA",nota:"Aquí es pronombre: la persona (tú cantas)."},
  {p:"… letra es muy clara.",ok:"Tu",d:["Tú"],cat:"DIACRITICA",nota:"Aquí es posesivo: lo que es tuyo (tu casa)."},
  {p:"¿Ya hiciste … tarea?",ok:"tu",d:["tú"],cat:"DIACRITICA",nota:"Aquí es posesivo: lo que es tuyo (tu casa)."},
  {p:"Gracias a …, ganamos el partido.",ok:"tú",d:["tu"],cat:"DIACRITICA",nota:"Aquí es pronombre: la persona (tú cantas)."},
  {p:"… hermano juega muy bien.",ok:"Tu",d:["Tú"],cat:"DIACRITICA",nota:"Aquí es posesivo: lo que es tuyo (tu casa)."},
  {p:"Ese regalo es para ….",ok:"él",d:["el"],cat:"DIACRITICA",nota:"Aquí es pronombre: un hombre o un niño (él juega)."},
  {p:"… autobús llegó tarde.",ok:"El",d:["Él"],cat:"DIACRITICA",nota:"Aquí es artículo: va antes de un sustantivo (el balón)."},
  {p:"Mi primo dice que … ganó la carrera.",ok:"él",d:["el"],cat:"DIACRITICA",nota:"Aquí es pronombre: un hombre o un niño (él juega)."},
  {p:"Dejé … libro en la mesa.",ok:"el",d:["él"],cat:"DIACRITICA",nota:"Aquí es artículo: va antes de un sustantivo (el balón)."},
  {p:"Llegó … maestro de Educación Física.",ok:"el",d:["él"],cat:"DIACRITICA",nota:"Aquí es artículo: va antes de un sustantivo (el balón)."},
  {p:"Dile a … que lo espero.",ok:"él",d:["el"],cat:"DIACRITICA",nota:"Aquí es pronombre: un hombre o un niño (él juega)."},
  {p:"… trajo los refrescos.",ok:"Él",d:["El"],cat:"DIACRITICA",nota:"Aquí es pronombre: un hombre o un niño (él juega)."},
  {p:"¿Esta carta es para …?",ok:"mí",d:["mi"],cat:"DIACRITICA",nota:"Aquí es pronombre, después de una preposición (para mí)."},
  {p:"… mamá trabaja en un hospital.",ok:"Mi",d:["Mí"],cat:"DIACRITICA",nota:"Aquí es posesivo o nota musical (mi casa)."},
  {p:"A … me gustan los tacos.",ok:"mí",d:["mi"],cat:"DIACRITICA",nota:"Aquí es pronombre, después de una preposición (para mí)."},
  {p:"Olvidé … mochila en el salón.",ok:"mi",d:["mí"],cat:"DIACRITICA",nota:"Aquí es posesivo o nota musical (mi casa)."},
  {p:"… perro se llama Canelo.",ok:"Mi",d:["Mí"],cat:"DIACRITICA",nota:"Aquí es posesivo o nota musical (mi casa)."},
  {p:"Eso no es para ….",ok:"mí",d:["mi"],cat:"DIACRITICA",nota:"Aquí es pronombre, después de una preposición (para mí)."},
  {p:"Toca la nota … en la flauta.",ok:"mi",d:["mí"],cat:"DIACRITICA",nota:"Aquí es posesivo o nota musical (mi casa)."},
  {p:"… estudias, vas a aprobar.",ok:"Si",d:["Sí"],cat:"DIACRITICA",nota:"Aquí es condición (si llueve, no salgo)."},
  {p:"Le pregunté y me dijo que ….",ok:"sí",d:["si"],cat:"DIACRITICA",nota:"Aquí es afirmación (sí quiero)."},
  {p:"No sé … podré ir mañana.",ok:"si",d:["sí"],cat:"DIACRITICA",nota:"Aquí es condición (si llueve, no salgo)."},
  {p:"¡Claro que … voy a la excursión!",ok:"sí",d:["si"],cat:"DIACRITICA",nota:"Aquí es afirmación (sí quiero)."},
  {p:"Dijo que … va al viaje.",ok:"sí",d:["si"],cat:"DIACRITICA",nota:"Aquí es afirmación (sí quiero)."},
  {p:"… terminas temprano, salimos a jugar.",ok:"Si",d:["Sí"],cat:"DIACRITICA",nota:"Aquí es condición (si llueve, no salgo)."},
  {p:"Ella … sabe la respuesta.",ok:"sí",d:["si"],cat:"DIACRITICA",nota:"Aquí es afirmación (sí quiero)."},
  {p:"Quiero … agua, por favor.",ok:"más",d:["mas"],cat:"DIACRITICA",nota:"Aquí es cantidad (más agua)."},
  {p:"Corrí … rápido que ayer.",ok:"más",d:["mas"],cat:"DIACRITICA",nota:"Aquí es cantidad (más agua)."},
  {p:"Lo intentó, … no pudo lograrlo.",ok:"mas",d:["más"],cat:"DIACRITICA",nota:"Aquí es significa «pero» (casi no se usa)."},
  {p:"Necesito … tiempo para terminar.",ok:"más",d:["mas"],cat:"DIACRITICA",nota:"Aquí es cantidad (más agua)."},
  {p:"Quería ir, … no tenía permiso.",ok:"mas",d:["más"],cat:"DIACRITICA",nota:"Aquí es significa «pero» (casi no se usa)."},
  {p:"Este examen fue … fácil.",ok:"más",d:["mas"],cat:"DIACRITICA",nota:"Aquí es cantidad (más agua)."},
  {p:"Mi abuela prepara … de canela.",ok:"té",d:["te"],cat:"DIACRITICA",nota:"Aquí es la bebida (un té caliente)."},
  {p:"¿… ayudo con la tarea?",ok:"Te",d:["Té"],cat:"DIACRITICA",nota:"Aquí es pronombre (te quiero)."},
  {p:"… espero a la salida.",ok:"Te",d:["Té"],cat:"DIACRITICA",nota:"Aquí es pronombre (te quiero)."},
  {p:"Me tomé un … de manzanilla.",ok:"té",d:["te"],cat:"DIACRITICA",nota:"Aquí es la bebida (un té caliente)."},
  {p:"… llamo en la tarde.",ok:"Te",d:["Té"],cat:"DIACRITICA",nota:"Aquí es pronombre (te quiero)."},
  {p:"El … verde se hace con hojas.",ok:"té",d:["te"],cat:"DIACRITICA",nota:"Aquí es la bebida (un té caliente)."},
  {p:"¿… gusta el helado?",ok:"Te",d:["Té"],cat:"DIACRITICA",nota:"Aquí es pronombre (te quiero)."},
  {p:"Pídele que te … la hoja.",ok:"dé",d:["de"],cat:"DIACRITICA",nota:"Aquí es del verbo dar (que me dé)."},
  {p:"La mochila … Luis es azul.",ok:"de",d:["dé"],cat:"DIACRITICA",nota:"Aquí es preposición (la casa de Ana)."},
  {p:"Ojalá el maestro nos … más tiempo.",ok:"dé",d:["de"],cat:"DIACRITICA",nota:"Aquí es del verbo dar (que me dé)."},
  {p:"Tengo un vaso … agua.",ok:"de",d:["dé"],cat:"DIACRITICA",nota:"Aquí es preposición (la casa de Ana)."},
  {p:"Espero que me … permiso.",ok:"dé",d:["de"],cat:"DIACRITICA",nota:"Aquí es del verbo dar (que me dé)."},
  {p:"Es una mesa … madera.",ok:"de",d:["dé"],cat:"DIACRITICA",nota:"Aquí es preposición (la casa de Ana)."},
  {p:"Dile que te … el cambio.",ok:"dé",d:["de"],cat:"DIACRITICA",nota:"Aquí es del verbo dar (que me dé)."},
  {p:"Yo … la respuesta.",ok:"sé",d:["se"],cat:"DIACRITICA",nota:"Aquí es del verbo saber (yo sé)."},
  {p:"El gato … subió al árbol.",ok:"se",d:["sé"],cat:"DIACRITICA",nota:"Aquí es pronombre (se fue)."},
  {p:"No … dónde dejé mis llaves.",ok:"sé",d:["se"],cat:"DIACRITICA",nota:"Aquí es del verbo saber (yo sé)."},
  {p:"Mi tío … compró un carro.",ok:"se",d:["sé"],cat:"DIACRITICA",nota:"Aquí es pronombre (se fue)."},
  {p:"… me olvidó la tarea.",ok:"Se",d:["Sé"],cat:"DIACRITICA",nota:"Aquí es pronombre (se fue)."},
  {p:"¡Ya … cómo resolverlo!",ok:"sé",d:["se"],cat:"DIACRITICA",nota:"Aquí es del verbo saber (yo sé)."},
  {p:"Ana … lavó las manos.",ok:"se",d:["sé"],cat:"DIACRITICA",nota:"Aquí es pronombre (se fue)."},
  {p:"¿… hora es?",ok:"Qué",d:["Que"],cat:"DIACRITICA",nota:"Aquí es pregunta o exclamación (¿qué haces?)."},
  {p:"Me dijo … llegaría tarde.",ok:"que",d:["qué"],cat:"DIACRITICA",nota:"Aquí es une dos ideas (dijo que vendría)."},
  {p:"¡… bonito día!",ok:"Qué",d:["Que"],cat:"DIACRITICA",nota:"Aquí es pregunta o exclamación (¿qué haces?)."},
  {p:"No sé … hacer con este problema.",ok:"qué",d:["que"],cat:"DIACRITICA",nota:"Aquí es pregunta o exclamación (¿qué haces?)."},
  {p:"El libro … me prestaste es increíble.",ok:"que",d:["qué"],cat:"DIACRITICA",nota:"Aquí es une dos ideas (dijo que vendría)."},
  {p:"¿… comiste hoy?",ok:"Qué",d:["Que"],cat:"DIACRITICA",nota:"Aquí es pregunta o exclamación (¿qué haces?)."},
  {p:"Quiero … vengas a mi fiesta.",ok:"que",d:["qué"],cat:"DIACRITICA",nota:"Aquí es une dos ideas (dijo que vendría)."},
  {p:"¡… calor hace!",ok:"Qué",d:["Que"],cat:"DIACRITICA",nota:"Aquí es pregunta o exclamación (¿qué haces?)."},
  {p:"¿… te llamas?",ok:"Cómo",d:["Como"],cat:"DIACRITICA",nota:"Aquí es pregunta por la manera (¿cómo estás?)."},
  {p:"Tengo hambre, por eso … mucho.",ok:"como",d:["cómo"],cat:"DIACRITICA",nota:"Aquí es compara o es del verbo comer (como pan)."},
  {p:"Explícame … resolviste el ejercicio.",ok:"cómo",d:["como"],cat:"DIACRITICA",nota:"Aquí es pregunta por la manera (¿cómo estás?)."},
  {p:"Corre … el viento.",ok:"como",d:["cómo"],cat:"DIACRITICA",nota:"Aquí es compara o es del verbo comer (como pan)."},
  {p:"¿… llegaste a la escuela?",ok:"Cómo",d:["Como"],cat:"DIACRITICA",nota:"Aquí es pregunta por la manera (¿cómo estás?)."},
  {p:"Es tan alto … su papá.",ok:"como",d:["cómo"],cat:"DIACRITICA",nota:"Aquí es compara o es del verbo comer (como pan)."},
  {p:"No sé … se llama.",ok:"cómo",d:["como"],cat:"DIACRITICA",nota:"Aquí es pregunta por la manera (¿cómo estás?)."},
  {p:"¿… está mi lápiz?",ok:"Dónde",d:["Donde"],cat:"DIACRITICA",nota:"Aquí es pregunta por el lugar (¿dónde estás?)."},
  {p:"Vivo … empieza la carretera.",ok:"donde",d:["dónde"],cat:"DIACRITICA",nota:"Aquí es señala un lugar, sin preguntar (vivo donde empieza el camino)."},
  {p:"No recuerdo … dejé mi suéter.",ok:"dónde",d:["donde"],cat:"DIACRITICA",nota:"Aquí es pregunta por el lugar (¿dónde estás?)."},
  {p:"La tienda … compramos el pan ya cerró.",ok:"donde",d:["dónde"],cat:"DIACRITICA",nota:"Aquí es señala un lugar, sin preguntar (vivo donde empieza el camino)."},
  {p:"¿De … eres?",ok:"dónde",d:["donde"],cat:"DIACRITICA",nota:"Aquí es pregunta por el lugar (¿dónde estás?)."},
  {p:"Esa es la casa … nací.",ok:"donde",d:["dónde"],cat:"DIACRITICA",nota:"Aquí es señala un lugar, sin preguntar (vivo donde empieza el camino)."},
  {p:"Dime … nos vemos.",ok:"dónde",d:["donde"],cat:"DIACRITICA",nota:"Aquí es pregunta por el lugar (¿dónde estás?)."},
  {p:"¿… es tu cumpleaños?",ok:"Cuándo",d:["Cuando"],cat:"DIACRITICA",nota:"Aquí es pregunta por el tiempo (¿cuándo llegas?)."},
  {p:"… termine la clase, salimos al patio.",ok:"Cuando",d:["Cuándo"],cat:"DIACRITICA",nota:"Aquí es señala un momento, sin preguntar (cuando llegues, avísame)."},
  {p:"Avísame … llegues a tu casa.",ok:"cuando",d:["cuándo"],cat:"DIACRITICA",nota:"Aquí es señala un momento, sin preguntar (cuando llegues, avísame)."},
  {p:"Pregúntale … es el examen.",ok:"cuándo",d:["cuando"],cat:"DIACRITICA",nota:"Aquí es pregunta por el tiempo (¿cuándo llegas?)."},
  {p:"¿… vienes a visitarnos?",ok:"Cuándo",d:["Cuando"],cat:"DIACRITICA",nota:"Aquí es pregunta por el tiempo (¿cuándo llegas?)."},
  {p:"Me pongo feliz … llueve.",ok:"cuando",d:["cuándo"],cat:"DIACRITICA",nota:"Aquí es señala un momento, sin preguntar (cuando llegues, avísame)."},
  {p:"No sé … regresa.",ok:"cuándo",d:["cuando"],cat:"DIACRITICA",nota:"Aquí es pregunta por el tiempo (¿cuándo llegas?)."},
  {p:"… no termino mi tarea.",ok:"Aún",d:["Aun"],cat:"DIACRITICA",nota:"Aquí es significa «todavía» (aún no llega)."},
  {p:"Fue a la escuela … estando enfermo.",ok:"aun",d:["aún"],cat:"DIACRITICA",nota:"Aquí es significa «incluso» (aun así)."},
  {p:"¿… tienes hambre?",ok:"Aún",d:["Aun"],cat:"DIACRITICA",nota:"Aquí es significa «todavía» (aún no llega)."},
  {p:"Todos vinieron, … los de tercero.",ok:"aun",d:["aún"],cat:"DIACRITICA",nota:"Aquí es significa «incluso» (aun así)."},
  {p:"¿… ganó el partido?",ok:"Quién",d:["Quien"],cat:"DIACRITICA",nota:"Aquí es pregunta por una persona (¿quién vino?)."},
  {p:"Fue Ana … encontró las llaves.",ok:"quien",d:["quién"],cat:"DIACRITICA",nota:"Aquí es se refiere a alguien, sin preguntar (fue él quien llamó)."},
  {p:"No sé … trajo el pastel.",ok:"quién",d:["quien"],cat:"DIACRITICA",nota:"Aquí es pregunta por una persona (¿quién vino?)."},
  {p:"El niño con … hablé es mi primo.",ok:"quien",d:["quién"],cat:"DIACRITICA",nota:"Aquí es se refiere a alguien, sin preguntar (fue él quien llamó)."},
  {p:"¿… es tu color favorito?",ok:"Cuál",d:["Cual"],cat:"DIACRITICA",nota:"Aquí es pregunta por una opción (¿cuál quieres?)."},
  {p:"Esa es la razón por la … llegué tarde.",ok:"cual",d:["cuál"],cat:"DIACRITICA",nota:"Aquí es se refiere a algo, sin preguntar (la razón por la cual)."},
  {p:"Elige … te gusta más.",ok:"cuál",d:["cual"],cat:"DIACRITICA",nota:"Aquí es pregunta por una opción (¿cuál quieres?)."},
  {p:"El parque en el … jugamos es enorme.",ok:"cual",d:["cuál"],cat:"DIACRITICA",nota:"Aquí es se refiere a algo, sin preguntar (la razón por la cual)."},
  {p:"¿… cuesta el cuaderno?",ok:"Cuánto",d:["Cuanto"],cat:"DIACRITICA",nota:"Aquí es pregunta o exclama una cantidad (¿cuánto cuesta?)."},
  {p:"¡… te extrañé!",ok:"Cuánto",d:["Cuanto"],cat:"DIACRITICA",nota:"Aquí es pregunta o exclama una cantidad (¿cuánto cuesta?)."},
  {p:"Come … quieras.",ok:"cuanto",d:["cuánto"],cat:"DIACRITICA",nota:"Aquí es cantidad sin preguntar (come cuanto quieras)."},
  {p:"… más estudio, más aprendo.",ok:"Cuanto",d:["Cuánto"],cat:"DIACRITICA",nota:"Aquí es cantidad sin preguntar (come cuanto quieras)."}
];
